<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "xtab_generator"
 *
 * Auto generated by Extension Builder 2018-01-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'CGB XTAB Generator',
    'description' => 'Versatile XTAB Generator for any Extbase based extension.',
    'category' => 'plugin',
    'author' => 'Christoph Balogh',
    'author_email' => 'cb@lustige-informatik.at',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.2-rc80528',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

/**
 * 8.7.2-rc80528
 * cleanup of plugin settings
 * 
 * 8.7.2-rc80524
 * introduced $sqlcore for better transparency of core query for help display
 * 
 * 8.7.2-rc80523
 * allow column mapping with FIELD() and ELT()
 * 
 * 8.7.2-rc80522
 * corrected headers when in rteverse row order
 * added possibility to cascade query expressions
 * 
 * 8.7.2.-rc80513
 * added possibility to refer to ###FEUSER_field### values in where clause
 * 
 * 8.7.2-rc80507
 * corrected transpose function
 */